version: "3"

services:

    mongo:
        container_name: mongo
        restart: always
        image: mongo:3.4
        command: --nojournal
        ports:
            - 127.0.0.1:27017:27017

    orion:
        container_name: orion
        restart: always
        image: fiware/orion:2.0.0
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - "1026:1026"
        command: -dbhost mongo

    iot-agent:
        container_name: fiware-iot-agent
        restart: always
        image: fiware/iotagent-ul:1.7.0
        hostname: iot-agent
        depends_on:
            - mongo
        expose:
            - "4041"
            - "7896"
        ports:
            - "4041:4041"
            - "7896:7896"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4041"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_LOG_LEVEL=DEBUG"
            - "IOTA_TIMESTAMP=true"
            - "IOTA_MONGO_HOST=mongo"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagentul"
            - "IOTA_HTTP_PORT=7896"
            - "IOTA_PROVIDER_URL=http://iot-agent:4041"
