version: "3"

services:

    orion:
        image: fiware/orion:2.4.0
        ports:
            - 1026:1026
        depends_on:
            - mongo
        command:
            -dbhost mongo
            -db orion

    mongo:
        image: mongo:3.6.16
        command: --nojournal --smallfiles
        volumes:
            - ./data/mongo-data:/data/db
