version: "3"

services:

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./data/wirecloud/wirecloud-static:/var/www/static:ro

        depends_on:
            - wirecloud

    wirecloud:
        image: fiware/wirecloud:1.3            
        depends_on:
            - postgres
            - elasticsearch
            - memcached
        environment:
            - DEBUG=false
            - LOGLEVEL=INFO
            - DB_HOST=postgres
            - DB_PASSWORD=wirepass
            - FORWARDED_ALLOW_IPS=*
            - ELASTICSEARCH2_URL=http://elasticsearch:9200/
            - MEMCACHED_LOCATION=memcached:11211
        volumes:
            - ./data/wirecloud/wirecloud-data:/opt/wirecloud_instance/data
            - ./data/wirecloud/wirecloud-static:/var/www/static

    elasticsearch:
        image: elasticsearch:2.4
        volumes:
            - ./data/wirecloud/elasticsearch-data:/usr/share/elasticsearch/data
        command: elasticsearch -Des.index.max_result_window=50000

    memcached:
        image: memcached:1
        command: memcached -m 2048m

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=wirepass
        volumes:
            - ./data/wirecloud/postgres-data:/var/lib/postgresql/data

    ngsiproxy:
        image: fiware/ngsiproxy:1.2.0
        ports:
            - 3000:3000

    orion:
        image: fiware/orion:2.4.0
        ports:
            - 1026:1026
        depends_on:
            - mongo
        command:
            -dbhost mongo
            -db orion

    mongo:
        image: mongo:3.6.16
        command: --nojournal --smallfiles
        volumes:
            - ./data/mongo-data:/data/db

    iot-agent:
        image: fiware/iotagent-ul:1.13.0
        restart: always
        depends_on:
            - mongo
            - mosquitto
        ports:
            - 4041:4041
        environment:
            - IOTA_CB_HOST=orion
            - IOTA_CB_PORT=1026
            - IOTA_NORTH_PORT=4041
            - IOTA_REGISTRY_TYPE=mongodb
            - IOTA_LOG_LEVEL=DEBUG
            - IOTA_TIMESTAMP=true
            - IOTA_CB_NGSI_VERSION=v2
            - IOTA_AUTOCAST=true
            - IOTA_MONGO_HOST=mongo
            - IOTA_MONGO_PORT=27017
            - IOTA_MONGO_DB=iotagentul
            - IOTA_MQTT_HOST=mosquitto
            - IOTA_MQTT_PORT=1883
            - IOTA_DEFAULT_RESOURCE=
            - IOTA_PROVIDER_URL=http://iot-agent:4041

    mosquitto:
        image: eclipse-mosquitto
        ports:
            - 1883:1883
            - 9001:9001
