version: "3"

services:

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./data/wirecloud/wirecloud-static:/var/www/static:ro

        depends_on:
            - wirecloud

    wirecloud:
        image: fisuda/wirecloud:1.3            
        depends_on:
            - postgres
            - elasticsearch
            - memcached
        environment:
            - DEBUG=false
            - LOGLEVEL=INFO
            - DB_HOST=postgres
            - DB_PASSWORD=wirepass
            - FORWARDED_ALLOW_IPS=*
            - ELASTICSEARCH2_URL=http://elasticsearch:9200/
            - MEMCACHED_LOCATION=memcached:11211
        volumes:
            - ./data/wirecloud/wirecloud-data:/opt/wirecloud_instance/data
            - ./data/wirecloud/wirecloud-static:/var/www/static

    elasticsearch:
        image: fisuda/elasticsearch:2.4
        volumes:
            - ./data/wirecloud/elasticsearch-data:/usr/share/elasticsearch/data
        command: elasticsearch -Des.index.max_result_window=50000

    memcached:
        image: memcached:1
        command: memcached -m 2048m

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_PASSWORD=wirepass
        volumes:
            - ./data/wirecloud/postgres-data:/var/lib/postgresql/data

    ngsiproxy:
        image: fisuda/ngsiproxy:1.2.0

    orion:
        image: fisuda/orion:2.4.0
        ports:
            - 1026:1026
        depends_on:
            - mongo
        command:
            -dbhost mongo
            -db orion

    mongo:
        image: mongo:3.6.16
        command: --nojournal --smallfiles
        volumes:
            - ./data/mongo-data:/data/db
