version: "3"

services:

    orion:
        image: fisuda/orion:2.4.0
        ports:
            - 1026:1026
        depends_on:
            - mongo
        command:
            -dbhost mongo
            -db orion

    mongo:
        image: mongo:3.6.16
        command: --nojournal --smallfiles
        volumes:
            - ./data/mongo-data:/data/db

    iot-agent:
        restart: always
        image: fiware/iotagent-json:1.14.0
        depends_on:
            - mongo
        ports:
            - 4041:4041
            - 7896:7896
        environment:
            - IOTA_CB_HOST=orion
            - IOTA_CB_PORT=1026
            - IOTA_NORTH_PORT=4041
            - IOTA_REGISTRY_TYPE=mongodb
            - IOTA_LOG_LEVEL=DEBUG
            - IOTA_TIMESTAMP=true
            - IOTA_CB_NGSI_VERSION=v2
            - IOTA_AUTOCAST=true
            - IOTA_MONGO_HOST=mongo
            - IOTA_MONGO_PORT=27017
            - IOTA_MONGO_DB=iotagentjson
            - IOTA_HTTP_PORT=7896
            - IOTA_PROVIDER_URL=http://iot-agent:4041
            # - IOTA_DEFAULT_RESOURCE=/iot/json
